### ISSUE TITLE
Validator not active in Neos 4.3

### ISSUE THREAD

**Issue by kdambekalns** [sinso/Swisscom.Neos.CaseInsensitiveUrls#10]
The validator for the uriPathSegment is no longer active in the React UI. But it might be easily replaced by overriding the existing validation to be case-sensitive:

```'yaml
Neos.Neos:Document':
  properties:
    uriPathSegment:
      validation:
        'Neos.Neos/Validation/RegularExpressionValidator':
          regularExpression: '/^[a-z0-9\-]+$/'
```

**Comment by lorenzulrich** [comment]
I just discussed this with @fanat98 (working for Swisscom) and he informed me that his branch doesn't work with Neos anymore. He agreed to transfer the package to us and we will prepare a new release with Neos 4.3/5 compatibility.
