### ISSUE TITLE
Neos 8 Compatibility

### ISSUE THREAD

**Issue by paavo** [sinso/Swisscom.Neos.CaseInsensitiveUrls#13]
Currently – as per composer.json – this package is not compatible with Neos 8.
Therefore we need to check / fix / update it.
If i find time, i'll try to update and see if it works.

**Comment by lorenzulrich** [comment]
I don't know if you tested it yet, but I think that nothing changed in this area, so I'll change the constraint to support Neos 8.
For Neos 9, the route path features changed so I think some adjustments will be necessary.

**Comment by lorenzulrich** [comment]
Resolved in https://github.com/visol/Visol.Neos.CaseInsensitiveUrls/commit/2e85d2228d60d98ad9fc1a20833d4662ed91b6e2.
