### ISSUE TITLE
Update Package to Neos 3.0

### ISSUE THREAD

**Issue by peterbucher** [sinso/Swisscom.Neos.CaseInsensitiveUrls#5]
Hi

I did update the package to Neos 3.0 and created the Branch "3.0" within my fork.
I cant make a pull request to a new "3.0" branch, as i have no permissions. But i would recommend to make a new branch.

After that, i will create a pull request to that branch.

To see what i did: [master to 3.0 comparison for pull request](https://github.com/sinso/Swisscom.Neos.CaseInsensitiveUrls/compare/sinso:master...belliconag:3.0)

The changes are quite a while in production. No issues till now :-)

**Comment by jrenggli** [comment]
Hi @peterbucher 
Thanks for posting your changes.

@fanat98, @simstern: As Neos 3.x is the current stable version I suggest to switch master of this package to be compatible with Neos 3.x. The former version could be kept in branches for 1.x or 2.x.

**Comment by peterbucher** [comment]
I like the proposal from @jrenggli 
Here is the pull request to the master branch #6

**Comment by fanat98** [comment]
hi @peterbucher
Thank you for changes and PR.
@jrenggli 
The former version is in 2.x tag and new in master and 3.0 tag.
it is ok so?

**Comment by peterbucher** [comment]
@fanat98 I think we both meant "branch".
master <- like it is now, the "3.0" branch
2.0 <- a branch which branches from the master before the 3.0 update merge
