### ISSUE TITLE
Latest version not available via Packagist

### ISSUE THREAD

**Issue by kdambekalns** [sinso/Swisscom.Neos.CaseInsensitiveUrls#8]
As mentioned in https://github.com/sinso/Swisscom.Neos.CaseInsensitiveUrls/pull/7#issuecomment-360807551 already, the package is not auto-updated on packagist.

Thus the merge of that PR is still not seen there and when trying to install the package via packagist, it reject anything above Neos 3.0 as not meeting the requirements.

Please enable the auto-update for Packagist in GitHub (https://packagist.org/about#how-to-update-packages) and try to tag releases in a meaningful way. Thanks!

**Comment by fanat98** [comment]
done
